/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import JoyStick from "./uiscript/JoyStick"
import LoadSceneScript from "./uiscript/LoadSceneScript"
import mainSceneUI from "./uiscript/mainSceneUI"
import RenderTextureShowUI from "./uiscript/RenderTextureShowUI"
import SceneSelectUI from "./uiscript/SceneSelectUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=750;
    static height:number=1334;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="mainScene.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("uiscript/JoyStick.ts",JoyStick);
        reg("uiscript/LoadSceneScript.ts",LoadSceneScript);
        reg("uiscript/mainSceneUI.ts",mainSceneUI);
        reg("uiscript/RenderTextureShowUI.ts",RenderTextureShowUI);
        reg("uiscript/SceneSelectUI.ts",SceneSelectUI);
    }
}
GameConfig.init();