/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class JoyStickUI extends Laya.Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("JoyStick");
        }
    }
    REG("ui.JoyStickUI",JoyStickUI);
    export class loadUI extends Laya.Scene {
		public bg:Laya.Image;
		public proYellow:Laya.Image;
		public proBlue:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("load");
        }
    }
    REG("ui.loadUI",loadUI);
    export class tipSceneUI extends Laya.Scene {
		public img_TipsLab:Laya.Image;
		public labTips:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("tipScene");
        }
    }
    REG("ui.tipSceneUI",tipSceneUI);
}